// models/Note.js
import mongoose from 'mongoose';

const noteSchema = new mongoose.Schema({
  user:  { type: mongoose.Schema.Types.ObjectId, ref: 'User',  required: true },
  topic: { type: mongoose.Schema.Types.ObjectId, ref: 'Topic', default: null },

  title:   { type: String, required: true, trim: true },
  content: { type: String, required: true },

  type: {
    type: String,
    enum: ['generated', 'custom', 'uploaded'],
    default: 'custom'
  },

  // If generated by AI — store the prompt that created it
  generatedFrom: { type: String, default: '' },

  tags: [{ type: String }]
}, {
  timestamps: true
});

noteSchema.index({ user: 1, createdAt: -1 });
noteSchema.index({ title: 'text', content: 'text' });

export default mongoose.model('Note', noteSchema);